name: Holograms
version: ${version}
description: A simple to use Hologram plugin
author: SainttX,KingTux
license: MIT
api-version: 1.13

main: com.sainttx.holograms.HologramPlugin
softdepend: [ Multiverse-Core, MultiWorld, WorldLoad ]

commands:
  holograms:
    description: All commands for Hologram
    aliases: [hologram, holo, h]
    permission-message: You do not have sufficient permissions to use this command

permissions:
  holograms.*:
    description: Gives access to all Auction commands
    children:
      holograms.create: true
      holograms.delete: true
      holograms.list: true
      holograms.near: true
      holograms.movehere: true
      holograms.addline: true
      holograms.removeline: true
      holograms.insertline: true
      holograms.info: true
  holograms.create:
    description: Allows players to create holograms
    default: op
  holograms.delete:
    description: Allows players to delete holograms
    default: op
  holograms.list:
    description: Allows players to list holograms
    default: op
  holograms.near:
    description: Allows players to view nearby holograms
    default: op
  holograms.movehere:
    description: Allows players to move holograms
    default: op
  holograms.addline:
    description: Allows players to add lines to holograms
    default: op
  holograms.removeline:
    description: Allows players to remove lines from holograms
    default: op
  holograms.insertline:
    description: Allows players to insert lines into holograms
    default: op
  holograms.info:
    description: Allows players to view a holograms info
    default: op
